server:
  port: 6060
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/billingservice
    username: ayderbek
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
  application:
    name: billing-service