server:
  port: 9098
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Spotify
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/musicservice
    username: ayderbek
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
  application:
    name: music-service
cloudfront:
  privateKeyPath: C:/Keys/pk-APKA43UPJH7H766E6EMC-pkcs8.pem
  domain: d2iujsfqj92c6r.cloudfront.net
aws:
  region: eu-central-1
  s3:
    buckets:
      spotify: spotifyspring

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    hostname: localhost
logging:
  level:
   com.ayderbek.musicservice.service: DEBUG
   org.springframework.web.socket: DEBUG

